# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'oneday' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for oneday
  pod 'IQKeyboardManager' #iOS8 and later

  # 主模块(必须)
  pod 'mob_sharesdk'
  
#  提示组件
  pod 'SVProgressHUD'
  # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#  pod 'mob_sharesdk/ShareSDKUI'

  # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
#  pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
#  pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
#//（微信sdk不带支付的命令）
  pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
  # pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' //（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
  
  # ShareSDKPlatforms模块其他平台，按需添加
#
#  pod 'mob_sharesdk/ShareSDKPlatforms/RenRen'
#  pod 'mob_sharesdk/ShareSDKPlatforms/AliPaySocial'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Kakao'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Yixin'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Messenger'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Copy'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Evernote'
#  pod 'mob_sharesdk/ShareSDKPlatforms/GooglePlus'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Instagram'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Instapaper'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Line'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Mail'
#  pod 'mob_sharesdk/ShareSDKPlatforms/SMS'
#  pod 'mob_sharesdk/ShareSDKPlatforms/WhatsApp'
#  pod 'mob_sharesdk/ShareSDKPlatforms/MeiPai'
#  pod 'mob_sharesdk/ShareSDKPlatforms/DingTalk'
#  pod 'mob_sharesdk/ShareSDKPlatforms/YouTube'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Dropbox'
#  pod 'mob_sharesdk/ShareSDKPlatforms/DingTalk'
#  pod 'mob_sharesdk/ShareSDKPlatforms/CMCC'
  pod 'mob_sharesdk/ShareSDKPlatforms/Telegram'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Reddit'
#  pod 'mob_sharesdk/ShareSDKPlatforms/DouBan'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Flickr'
#  pod 'mob_sharesdk/ShareSDKPlatforms/KaiXin'
#  pod 'mob_sharesdk/ShareSDKPlatforms/LinkedIn'
#  pod 'mob_sharesdk/ShareSDKPlatforms/MingDao'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Pinterest'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Pocket'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Print'
#  pod 'mob_sharesdk/ShareSDKPlatforms/TencentWeibo'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Tumblr'
#  pod 'mob_sharesdk/ShareSDKPlatforms/VKontakte'
#  pod 'mob_sharesdk/ShareSDKPlatforms/YouDaoNote'
#  pod 'mob_sharesdk/ShareSDKPlatforms/ESurfing'
#  pod 'mob_sharesdk/ShareSDKPlatforms/FacebookAccount'
#  pod 'mob_sharesdk/ShareSDKPlatforms/Douyin'

  # 使用配置文件分享模块（非必需）
#  pod 'mob_sharesdk/ShareSDKConfigFile'
#
#  # 扩展模块（在调用可以弹出我们UI分享方法的时候是必需的）
#  pod 'mob_sharesdk/ShareSDKExtension'
rn_path = '../node_modules/react-native'

pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
pod 'React', path: rn_path, subspecs: [
'Core',
'CxxBridge',
'DevSupport',
'RCTActionSheet',
'RCTAnimation',
'RCTGeolocation',
'RCTImage',
'RCTLinkingIOS',
'RCTNetwork',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTWebSocket',
]
pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "React"
            target.remove_from_project
        end
    end
end
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

end
